"""add translation column

Revision ID: 12f28acd1e2d
Revises: f5f8ccf16d39
Create Date: 2026-01-30 15:11:34.446442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f28acd1e2d'
down_revision = 'f5f8ccf16d39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('translation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'translation')
    # ### end Alembic commands ###
