"""Add saved_words table

Revision ID: f5f8ccf16d39
Revises: 6114eb663c7d
Create Date: 2026-01-29 21:07:39.603645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f8ccf16d39'
down_revision = '6114eb663c7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_words_id'), 'saved_words', ['id'], unique=False)
    op.create_index(op.f('ix_saved_words_user_id'), 'saved_words', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_words_user_id'), table_name='saved_words')
    op.drop_index(op.f('ix_saved_words_id'), table_name='saved_words')
    op.drop_table('saved_words')
    # ### end Alembic commands ###
